# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-13 12:36
from __future__ import unicode_literals

from django.db import migrations

def make_groups(apps, schema_editor):
    Group = apps.get_model('courses', 'Group')
    StudentEnrollment = apps.get_model('courses', 'StudentEnrollment')
    observed, nonobserved = {}, {}
    for enrollment in StudentEnrollment.objects.all():
        if enrollment.observed:
            observed.setdefault(enrollment.course, set()).add(enrollment.user)
        else:
            nonobserved.setdefault(enrollment.course, set()).add(enrollment.user)
    for course, students in observed.items():
        if students:
            group = Group(title='Opazovani', course=course)
            group.save()
            group.members.add(*students)
            group.save()
    for course, students in nonobserved.items():
        if students:
            group = Group(title='Skriti', course=course)
            group.save()
            group.members.add(*students)
            group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_group'),
    ]

    operations = [
        migrations.RunPython(make_groups)
    ]
