# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-09 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20170409_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_id', through='courses.AddAMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
