# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-12 15:59
from __future__ import unicode_literals

from django.db import migrations

def make_groups(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Group = apps.get_model('courses', 'Group')
    AddAMember = apps.get_model('courses', 'AddAMember')
    User = apps.get_model('users', 'User')
    StudentEnrollment = apps.get_model('courses', 'StudentEnrollment')
    for course in Course.objects.all():
        ime = 'Grupa {0}'.format(course.title)
        g = Group(title=ime, description='')
        g.save()
        #uporabniki = course.observed_students()
        uporabniki = User.objects.filter(studentenrollment__course=course, studentenrollment__observed=True)
        for u in uporabniki:
            r = AddAMember(group=g, user = u)
            r.save()
    
    


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20170409_1736'),
    ]

    operations = [
        migrations.RunPython(make_groups)
    ]
